Models/Summernote.cs
namespace App.Models
{
    public class Summernote
    {
        public Summernote(string id, bool isLoaded = true)
        {
            Id = id;
            IsLoaded = isLoaded;
        }

        public string Id { get; set; }
        public bool IsLoaded { get; set; }

        public int height { get; set; } = 120;
        public string toolbar {get; set; } = @"[
                ['style', ['bold', 'italic', 'underline', 'clear']],
                ['font', ['strikethrough', 'superscript', 'subscript']],
                ['fontsize', ['fontsize']],
                ['color', ['color']],
                ['insert', ['link', 'elfinder']],
                ['para', ['ul', 'ol', 'paragraph']],
                ['height', ['height']],
                ['view', ['fullscreen', 'codeview', 'help']]
                ]";

    }
}

Areas/Blog/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using App.Areas.Blog.Models;
using App.Data;
using Microsoft.AspNetCore.Authorization;
using App.Models;
using Microsoft.AspNetCore.Identity;
using App.Utilities;

namespace App.Areas.Blog.Controllers
{   
    [Area("Blog")]
    [Route("/Admin/Blog/Post/{action=Index}/{id?}")]
    [Authorize(Roles = RoleName.Administrator+ ","+RoleName.Editor)]
    public class PostController : Controller
    {
        private readonly AppDbContext _context;
        private readonly UserManager<AppUser> _userManager;

        public PostController(AppDbContext context, UserManager<AppUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        [TempData]
        public string StatusMessage {get; set;}

        // GET: Post
        public async Task<IActionResult> Index([FromQuery(Name = "p")]int currentPage, int pageSize)
        {
            var posts = _context.Posts.Include(p => p.Author)
                                      .OrderByDescending(p => p.DateUpdated);
            int totalPosts = posts.Count();
            if(pageSize <= 0) pageSize = 10;
            
            int countPages = (int)Math.Ceiling((double)totalPosts / pageSize);
            if (currentPage > countPages) currentPage = countPages;
            if (currentPage < 1) currentPage = 1;

            var pagingModel = new PagingModel()
            {
                countpages = countPages,
                currentpage = currentPage,
                generateUrl = (pageNumber) => Url.Action("Index", new {
                    p = pageNumber,
                    pageSize = pageSize
                })
            };

            ViewBag.pagingModel = pagingModel;
            ViewBag.totalPosts = totalPosts;

            var postsInPage = await posts.Skip((currentPage - 1) * pageSize)
                        .Take(pageSize)
                        .Include(p => p.PostCategories)
                        .ThenInclude(pc => pc.Category)
                        .ToListAsync();
            // model.totalUsers = await qr.CountAsync();
            // model.countPages = (int)Math.Ceiling((double)model.totalUsers / model.ITEMS_PER_PAGE);

            // if (model.currentPage < 1)
            //     model.currentPage = 1;
            // if (model.currentPage > model.countPages)
            //     model.currentPage = model.countPages;

            // var qr1 = qr.Skip((model.currentPage - 1) * model.ITEMS_PER_PAGE)
            //             .Take(model.ITEMS_PER_PAGE)
            //             .Select(u => new UserAndRole() {
            //                 Id = u.Id,
            //                 UserName = u.UserName,
            //             });
            return View(postsInPage);
        }

        // GET: Post/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Posts == null)
            {
                return NotFound();
            }

            var post = await _context.Posts
                .Include(p => p.Author)
                .FirstOrDefaultAsync(m => m.PostId == id);
            if (post == null)
            {
                return NotFound();
            }

            return View(post);
        }

        // GET: Post/Create
        public async Task<IActionResult> Create()
        {
            var categories = await _context.Categories.ToListAsync();
            ViewData["listCategory"] = new MultiSelectList(categories, "Id", "Title");
            return View();
        }

        // POST: Post/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Title,Description,Slug,Content,Published,listCategoryId")] CreatePostModel post)
        {
             var categories = await _context.Categories.ToListAsync();
            ViewData["listCategory"] = new MultiSelectList(categories, "Id", "Title");
            if(post.Slug == null)
            {
                post.Slug = AppUtilities.GenerateSlug(post.Title);
            }
            if(await _context.Posts.AnyAsync(p => p.Slug == post.Slug))
            {
                ModelState.AddModelError("Slug", "URL bị trùng, nhập URL khác!!!");
                return View(post);
            }
            if (ModelState.IsValid)
            {
                var user = await _userManager.GetUserAsync(this.User);
                post.DateCreated = post.DateUpdated = DateTime.Now;
                post.AuthorId = user.Id;
                _context.Posts.Add(post);
                // await _context.SaveChangesAsync();
                
                if(post.listCategoryId != null)
                {
                    foreach (var id in post.listCategoryId)
                    {
                        var postCate = new PostCategory()
                        {
                            Post = post,
                            CategoryID = id
                        };
                        System.Console.WriteLine("*************************************");
                         System.Console.WriteLine("new postID =",postCate.PostID);
                        _context.PostCategories.Add(postCate);
                    }
                   
                }

                await _context.SaveChangesAsync();
                StatusMessage = "Vừa thêm bài viết mới";
                return RedirectToAction(nameof(Index));
            }

            return View(post);
        }

        // GET: Post/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Posts == null)
            {
                return NotFound();
            }

            // var post = await _context.Posts.FindAsync(id);
            var post = await _context.Posts.Include(p => p.PostCategories).FirstOrDefaultAsync(p => p.PostId == id);
            if (post == null)
            {
                return NotFound();
            }
            var postEditModel = new CreatePostModel()
            {
                PostId = post.PostId,
                Title = post.Title,
                Content = post.Content,
                Description = post.Description,
                Slug = post.Slug,
                Published = post.Published,
                listCategoryId = post.PostCategories.Select(pc => pc.CategoryID).ToList()
            };
             var categories = await _context.Categories.ToListAsync();
            ViewData["categories"] = new MultiSelectList(categories, "Id", "Title");
            return View(postEditModel);
        }

        // POST: Post/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PostId,Title,Description,Slug,Content,Published, listCategoryId")] CreatePostModel post)
        {
            if (id != post.PostId)
            {
                return NotFound();
            }
            var categories = await _context.Categories.ToListAsync();
            ViewData["listCategoryId"] = new MultiSelectList(categories, "Id", "Title");

            if(post.Slug == null)
            {
                post.Slug = AppUtilities.GenerateSlug(post.Title);
            }
            if(await _context.Posts.AnyAsync(p => p.Slug == post.Slug && p.PostId != id))
            {
                ModelState.AddModelError("Slug", "URL bị trùng, nhập URL khác!!!");
                return View(post);
            }
            if (ModelState.IsValid)
            {
                try
                {
                    var postUpdate = await _context.Posts.Include(p => p.PostCategories).FirstOrDefaultAsync(p => p.PostId == id);
                    if(postUpdate == null)
                    {
                        return NotFound();
                    }
                    postUpdate.Title = post.Title;
                    postUpdate.Description = post.Description;
                    postUpdate.Content = post.Content;
                    postUpdate.DateUpdated = DateTime.Now;
                    postUpdate.Published = post.Published;
                    postUpdate.Slug = post.Slug;

                    //Update Post Category
                    if(post.listCategoryId == null) post.listCategoryId = new List<int>();
                    var oldCates =  postUpdate.PostCategories.Select(c => c.CategoryID).ToList();
                    var newCates = post.listCategoryId;

                    //Cac cate can loai bo
                    var removedCates = from c in postUpdate.PostCategories
                                      where (!newCates.Contains(c.CategoryID))
                                      select c;
                    _context.PostCategories.RemoveRange(removedCates);
                    //Cac cate can them vao
                    var addedCates = from c in newCates
                                   where (!oldCates.Contains(c))
                                   select c;
                    foreach (var cateId in addedCates)
                    {
                        _context.PostCategories.Add(new PostCategory()
                        {
                            PostID = id,
                            CategoryID = cateId
                        });
                    }

                    // _context.Update(post);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)

Areas/Blog/Controllers/ViewPostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using App.Areas.Blog.Models;
using App.Data;
using App.Models;
using App.Models.Blog;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Caching.Memory;

namespace BasicMVC.Areas_Blog_Controllers
{
    [Area("Blog")]
    [Route("/posts")]
    public class ViewPostController : Controller
    {

        private readonly ILogger<ViewPostController> _logger;
        private readonly AppDbContext _context;
        private IMemoryCache _cache;


        // Số bài hiện thị viết trên một trang danh mục
        public const int ITEMS_PER_PAGE = 4;

        public ViewPostController(ILogger<ViewPostController> logger,
            AppDbContext context,
            IMemoryCache cache)
        {
            _logger = logger;
            _context = context;
            _cache = cache;
        }

        [Route("{slug?}", Name = "listpost")]
        public IActionResult Index([FromRoute(Name = "slug")] string slugCategory, [FromQuery(Name = "p")]int currentPage, int pageSize)
        {

            var categories = GetCategories();

            Category category = null;
            if (!string.IsNullOrEmpty(slugCategory))
            {

                category = FindCategoryBySlug(categories, slugCategory);
                if (category == null)
                {
                    return NotFound("Không thấy Category");
                }

            }
            ViewData["categories"] = categories;
            ViewData["slugCategory"] = slugCategory;
            ViewData["CurrentCategory"] = category;


            // ........................................
            // Truy vấn lấy các post
            var posts = _context.Posts
                .Include(p => p.Author) // Load Author cho post  
                .Include(p => p.PostCategories) // Load các Category của Post
                .ThenInclude(c => c.Category)
                .AsQueryable();

            if (category != null)
            {

                var ids = category.ChildCategoryIDs();
                ids.Add(category.Id);

                // Lọc các Post có trong category (và con của nó)
                posts = posts.Where(p => p.PostCategories
                    .Where(c => ids.Contains(c.CategoryID)).Any());

            }

            int totalPosts = posts.Count();
            if(pageSize <= 0) pageSize = 10;
            
            int countPages = (int)Math.Ceiling((double)totalPosts / pageSize);
            if (currentPage > countPages) currentPage = countPages;
            if (currentPage < 1) currentPage = 1;

            var pagingModel = new PagingModel()
            {
                countpages = countPages,
                currentpage = currentPage,
                generateUrl = (pageNumber) => Url.Action("Index", new {
                    p = pageNumber,
                    pageSize = pageSize
                })
            };

            var postsInPage = posts.Skip((currentPage - 1) * pageSize)
                        .Take(pageSize);

            ViewBag.pagingModel = pagingModel;
            ViewBag.totalPosts = totalPosts;

            

            // Thực hiện truy vấn lấy List các Post và chuyển cho View
            return View(postsInPage.ToList());
        }

        [Route("post/{postSlug}")]
        public IActionResult Details(string postSlug)
        {
            var categories = GetCategories();
            ViewBag.categories = categories;

            var post = _context.Posts.Where(p => p.Slug == postSlug)
                       .Include(p => p.Author)
                       .Include(p => p.PostCategories)
                       .ThenInclude(pc => pc.Category)
                       .FirstOrDefault();
            if (post == null)
            {
                return NotFound();
            }
            Category category = post.PostCategories.FirstOrDefault()?.Category;
            ViewBag.category = category;

            var relativePosts = _context.Posts.Where(p => p.PostCategories.Any(pc => pc.CategoryID == category.Id))
                                              .Where(p => p.PostId != post.PostId)
                                              .OrderBy(p => p.DateUpdated)
                                              .Take(5)
                                              .ToList();
            ViewBag.relativePosts = relativePosts;

            return View(post);
        }

        [NonAction]
        List<Category> GetCategories()
        {

            List<Category> categories;

            string keycacheCategories = "_listallcategories";

            // Phục hồi categories từ Memory cache, không có thì truy vấn Db
            if (!_cache.TryGetValue(keycacheCategories, out categories))
            {

                categories = _context.Categories
                    .Include(c => c.CategoryChildren)
                    .AsEnumerable()
                    .Where(c => c.ParentCategory == null)
                    .ToList();

                // Thiết lập cache - lưu vào cache
                var cacheEntryOptions = new MemoryCacheEntryOptions()
                    .SetSlidingExpiration(TimeSpan.FromMinutes(300));
                _cache.Set("_GetCategories", categories, cacheEntryOptions);
            }

            return categories;
        }


        // Tìm (đệ quy) trong cây, một Category theo Slug
        [NonAction]
        Category FindCategoryBySlug(List<Category> categories, string Slug)
        {

            foreach (var c in categories)
            {
                if (c.Slug == Slug) return c;
                var c1 = FindCategoryBySlug(c.CategoryChildren.ToList(), Slug);
                if (c1 != null)
                    return c1;
            }

            return null;
        }
    }
}

Views/Shared/_AlertMessage.cshtml
@{
    var msg = TempData["StatusMessage"] as string;
}

@if(!string.IsNullOrEmpty(msg))
{
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        @msg
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span arial-hidden="true">&times;</span>
        </button>
    </div>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BasicMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BasicMVC.styles.css" asp-append-version="true" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark border-bottom box-shadow mb-3 app-navbar">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><strong>BasicMVC</strong></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Blog" asp-controller="ViewPost" asp-action="Index">Post</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                    <partial name="_MenuManagePartial" />
                    
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer">
        <div class="container">
            &copy; 2023 - BasicMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_MenuManagePartial.cshtml
@using Microsoft.AspNetCore.Authorization
@inject IAuthorizationService service

@{
  var result = await service.AuthorizeAsync(this.User, "ShowAdminMenu");
}
@if (result.Succeeded)
{
  <div class="dropdown">
    <button onclick="myFunction()" class="dropbtn btn btn-outline-danger dropdown-toggle"><strong>Manage</strong></button>
    <div id="myDropdown" class="dropdown-content dropdown-menu-right">
      <a class="dropdown-item" asp-controller="DbManage" action="Index" asp-area="Database">Database</a>
      <a class="dropdown-item" asp-controller="Contact" action="Index" asp-area="Contact">Contact</a>
      <a class="dropdown-item" asp-controller="Role" action="Index" asp-area="Identity">Role</a>
      <a class="dropdown-item" asp-controller="User" action="Index" asp-area="Identity">User</a>
      <a class="dropdown-item" asp-controller="Category" action="Index" asp-area="Blog">Blog Category</a>
      <a class="dropdown-item" asp-area="Blog" asp-controller="Post" asp-action="Index">Post</a>
      <a target="_blank" class="dropdown-item" asp-controller="FileManager" action="Index" asp-area="Files">Files</a>
    </div>

  </div>
}


<style>
  /* The container <div> - needed to position the dropdown content */
  .dropdown {
    position: relative;
    display: inline-block;
  }

  /* Dropdown Content (Hidden by Default) */
  .dropdown-content {
    display: none;
    position: absolute;
    right: 0;
    background-color: #f9f9f9;
    min-width: 160px;
    box-shadow: 0px 8px 16px 0px rgba(0, 0, 0, 0.2);
    z-index: 1;
  }

  /* Links inside the dropdown */
  .dropdown-content a {
    color: black;
    padding: 12px 16px;
    text-decoration: none;
    display: block;
  }

  /* Change color of dropdown links on hover */
  .dropdown-content a:hover {
    background-color: #ddd;
  }

  /* Show the dropdown menu (use JS to add this class to the .dropdown-content container when the user clicks on the dropdown button) */
  .show {
    display: block;
  }
</style>

<script>
  /* When the user clicks on the button,
toggle between hiding and showing the dropdown content */
  function myFunction() {
    document.getElementById("myDropdown").classList.toggle("show");
  }

  // Close the dropdown menu if the user clicks outside of it
  window.onclick = function (event) {
    if (!event.target.matches('.dropbtn')) {
      var dropdowns = document.getElementsByClassName("dropdown-content");
      var i;
      for (i = 0; i < dropdowns.length; i++) {
        var openDropdown = dropdowns[i];
        if (openDropdown.classList.contains('show')) {
          openDropdown.classList.remove('show');
        }
      }
    }
  }
</script>

Views/Shared/_PagingXTL.cshtml
@* 
    Model:
      - currentPage:int - Trang hiện tại
      - countPages:int - tổng số trang
      - generateUrl:delegate Func<int?, string> trả về URL tương ứng với trang p (1,2,3 ...)
*@

@model App.Models.PagingModel
@{
    int currentPage  = Model.currentpage;
    int countPages   = Model.countpages;
    var generateUrl  = Model.generateUrl;


    
    if (currentPage > countPages) 
      currentPage = countPages;

    if (countPages <= 1) return;
    

    int? preview = null;
    int? next = null;

    if (currentPage > 1)
        preview = currentPage - 1;

    if (currentPage < countPages)
        next = currentPage + 1;

    // Các trang hiện thị trong điều hướng
    List<int> pagesRanges = new List<int>();    

        
    int delta      = 5;             // Số trang mở rộng về mỗi bên trang hiện tại     
    int remain     = delta * 2;     // Số trang hai bên trang hiện tại

    pagesRanges.Add(currentPage);
    // Các trang phát triển về hai bên trang hiện tại
    for (int i = 1; i <= delta; i++)
    {
        if (currentPage + i  <= countPages) {
            pagesRanges.Add(currentPage + i); 
            remain --;
        }
               
        if (currentPage - i >= 1) {
            pagesRanges.Insert(0, currentPage - i);
            remain --;
        }
            
    }    
    // Xử lý thêm vào các trang cho đủ remain 
    //(xảy ra ở đầu mút của khoảng trang không đủ trang chèn  vào)
    if (remain > 0) {
        if (pagesRanges[0] == 1) {
            for (int i = 1; i <= remain; i++)
            {
                if (pagesRanges.Last() + 1 <= countPages) {
                    pagesRanges.Add(pagesRanges.Last() + 1);
                }
            }
        }
        else {
            for (int i = 1; i <= remain; i++)
            {
                if (pagesRanges.First() - 1 > 1) {
                    pagesRanges.Insert(0, pagesRanges.First() - 1);
                }
            }
        }
    }

}

@* PHÁT SINH HTML*@

<ul class="pagination">
    <!-- Previous page link -->
    @if (preview != null)
    {
        <li class="page-item">
            <a class="page-link" href="@generateUrl(preview)">Trang trước</a>
        </li>
    }
    else
    {
        <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Trang trước</a>
        </li>
    }
      
    <!-- Numbered page links -->
    @foreach (var pageitem in pagesRanges)
    {
        if (pageitem != currentPage) {
            <li class="page-item">
                <a class="page-link" href="@generateUrl(pageitem)">
                    @pageitem
                </a>
            </li>
        }   
        else 
        {
            <li class="page-item active" aria-current="page">
                <a class="page-link" href="#">@pageitem <span class="sr-only">(current)</span></a>
            </li>
        }
    }


    <!-- Next page link -->
    @if (next != null)
    {
        <li class="page-item">
            <a class="page-link" href="@generateUrl(next)">Trang sau</a>
        </li>
    }
    else 
    {
        <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Trang sau</a>
        </li>
    }
</ul>

Views/Shared/_StatusMessage.cshtml
@{
    var mgs = TempData["StatusMessage"] as string;
}

@if (!String.IsNullOrEmpty(mgs))
{
    var statusMessageClass = mgs.StartsWith("Error") ? "danger" : "success";
    <div class="alert alert-@statusMessageClass alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        @mgs
    </div>
}

Views/Shared/_Summernote.cshtml
@model App.Models.Summernote

@if (Model.IsLoaded)
{
    <script src="~/lib/summernote/summernote-bs4.min.js"></script>
    <link rel="stylesheet" href="~/lib/summernote/summernote-bs4.min.css" />
    <link rel="stylesheet" href="~/lib/jqueryui/themes/base/theme.css" />
    <link rel="stylesheet" href="~/lib/jqueryui/themes/base/jquery-ui.css" />
    <link rel="stylesheet" href="~/lib/elfinder/css/elfinder.full.css" />
    <link rel="stylesheet" href="~/lib/elfinder/css/theme.min.css" />
    <script src="~/lib/jqueryui/jquery-ui.min.js"></script>
    <script src="~/lib/elfinder/js/elfinder.min.js"></script>
}

<script>
    (function (factory) {
        if (typeof define === 'function' && define.amd) {
            define(['jquery'], factory);
        } 
        else if (typeof module === 'object' && module.exports) {
            module.exports = factory(require('jquery'));
        } else {
            factory(window.jQuery);
        }
    }(function ($) {
      $.extend($.summernote.plugins, {
            // Tạo plugin tên elfinder  
            'elfinder': function (context) {
                var self = this;
                // ui has renders to build ui elements.
                var ui = $.summernote.ui;
                // Tạo nút bấm
                context.memo('button.elfinder', function () {
                    var button = ui.button({
                        contents: '<i class="note-icon-picture"/>',
                        tooltip: 'Quản lý file',
                        click: function () {
                            // Bấm vào nút bấm gọi hàm elfinderDialog   
                            elfinderDialog(context); 
                        }
                    });
                    // create jQuery object from button instance.
                    var $elfinder = button.render();
                    return $elfinder;
                });
                // This methods will be called when editor is destroyed by $('..').summernote('destroy');
                // You should remove elements on `initialize`.
                this.destroy = function () {
                    this.$panel.remove();
                    this.$panel = null;
                };
            }
      
        });
    }));

    $(document).ready(function () {
        $('#@Model.Id').summernote({
            height: @Model.height,
            toolbar: @Html.Raw(Model.toolbar)
        });
    });

    function elfinderDialog(editor) {
  	    var fm = $('<div/>').dialogelfinder({
  		baseUrl: "@Url.Content("~/lib/elfinder/")",
                url: "@Url.Action("Connector", "FileManager", new {area = "Files"})",
  		lang : 'vi',
  		width : 840,
  		height: 450,
  		destroyOnClose : true,
  		getFileCallback : function(files, fm) {
  			console.log(files);
                        editor.invoke('editor.insertImage', files.url);
  		},
  		commandsOptions : {
  			getfile : {
  			    oncomplete : 'close',
  			    folders : false
  			}
  		}
  	}).dialogelfinder('instance');
}
</script>